sudo: true
language: python

python:
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - python createDB.py
  - py.test
  - pylint codegolf || true

notifications:
  email: false
  slack:
    rooms:
      - uqcs:V9gB7LhPmGARkyQZOpGEHza7#codegolf
  webhooks:
    urls:
      - hooks.uqcs.org.au/codegolf
    on_failure: never
    on_start: never
