sudo: true
language: python

python:
  - "3.4"
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y pylint

install:
  - pip install -r requirements.txt

script:
  - py.test
  - pylint codegolf