sudo: true
language: python

python:
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - py.test
  - pylint codegolf || true

notifications:
  slack:
    rooms:
      - uqcs:V9gB7LhPmGARkyQZOpGEHza7#codegolf
